In [1]:
#Importing pandas library with an alias name as 'pd'.
import pandas as pd
data=pd.read_csv('drug200.csv') #reading the csv file to data variable with the help of pandas.

In [2]:
#Viewing the first 10 entries of the data frame (data).
data.head(10)

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY
5   22   F  NORMAL        HIGH    8.607  drugX
6   49   F  NORMAL        HIGH   16.275  DrugY
7   41   M     LOW        HIGH   11.037  drugC
8   60   M  NORMAL        HIGH   15.171  DrugY
9   43   M     LOW      NORMAL   19.368  DrugY

In [3]:
#To check whether any empty values present in the (data) dataset.
data.isna().any()

Age            False
Sex            False
BP             False
Cholesterol    False
Na_to_K        False
Drug           False
dtype: bool

In [4]:
#To check whether any null values present in the (data) dataset.
data.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [5]:
#Viewing the entire information of the dataset.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


# **Dependent and Independent variable allocation**

In [6]:
X=data.iloc[:,0:5].values #Variable that contains matrix of independent features.
y=data.iloc[:,5].values #Variable that contains vector of dependent features.

In [7]:
X

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.113999999999999],
       [28, 'F', 'NORMAL', 'HIGH', 7.797999999999999],
       [61, 'F', 'LOW', 'HIGH', 18.043],
       [22, 'F', 'NORMAL', 'HIGH', 8.607000000000001],
       [49, 'F', 'NORMAL', 'HIGH', 16.275],
       [41, 'M', 'LOW', 'HIGH', 11.037],
       [60, 'M', 'NORMAL', 'HIGH', 15.171],
       [43, 'M', 'LOW', 'NORMAL', 19.368],
       [47, 'F', 'LOW', 'HIGH', 11.767000000000001],
       [34, 'F', 'HIGH', 'NORMAL', 19.199],
       [43, 'M', 'LOW', 'HIGH', 15.376],
       [74, 'F', 'LOW', 'HIGH', 20.941999999999997],
       [50, 'F', 'NORMAL', 'HIGH', 12.703],
       [16, 'F', 'HIGH', 'NORMAL', 15.515999999999998],
       [69, 'M', 'LOW', 'NORMAL', 11.455],
       [43, 'M', 'HIGH', 'HIGH', 13.972000000000001],
       [23, 'M', 'LOW', 'HIGH', 7.297999999999999],
       [32, 'F', 'HIGH', 'NORMAL', 25.974],
       [57, 'M', 'LOW', 'NORMAL', 19.128],
       [63, 'M

As we can able to see there are some categorical and binary values in our dependent and independent variables which we need to encode it before we are going to fitting into our model.

In [8]:
from sklearn.preprocessing import LabelEncoder #Importing labelencoder class from scikit learn library
l1=LabelEncoder() #Instantiating the labelencoder class as l1
l2=LabelEncoder() #Instantiating the labelencoder class as l2
l3=LabelEncoder() #Instantiating the labelencoder class as l3
l4=LabelEncoder() #Instantiating the labelencoder class as l4
X[:,1]=l1.fit_transform(X[:,1]) #Encoding the gender(sex) feature in our independent variable. 
X[:,2]=l2.fit_transform(X[:,2]) #Encoding the Blood pressure level feature in our independent variable.
X[:,3]=l3.fit_transform(X[:,3]) #Encoding the Choloestrol level feature in our independent variable.
y=l4.fit_transform(y) #Encoding the Drug feature in our dependent variable.

In [9]:
X #Viewing the independent variable after encoding.

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.113999999999999],
       [28, 0, 2, 0, 7.797999999999999],
       [61, 0, 1, 0, 18.043],
       [22, 0, 2, 0, 8.607000000000001],
       [49, 0, 2, 0, 16.275],
       [41, 1, 1, 0, 11.037],
       [60, 1, 2, 0, 15.171],
       [43, 1, 1, 1, 19.368],
       [47, 0, 1, 0, 11.767000000000001],
       [34, 0, 0, 1, 19.199],
       [43, 1, 1, 0, 15.376],
       [74, 0, 1, 0, 20.941999999999997],
       [50, 0, 2, 0, 12.703],
       [16, 0, 0, 1, 15.515999999999998],
       [69, 1, 1, 1, 11.455],
       [43, 1, 0, 0, 13.972000000000001],
       [23, 1, 1, 0, 7.297999999999999],
       [32, 0, 0, 1, 25.974],
       [57, 1, 1, 1, 19.128],
       [63, 1, 2, 0, 25.916999999999998],
       [47, 1, 1, 1, 30.568],
       [48, 0, 1, 0, 15.036],
       [33, 0, 1, 0, 33.486],
       [28, 0, 0, 1, 18.809],
       [31, 1, 0, 0, 30.366],
       [49, 0, 2, 1, 9.381],
       [39, 0, 1, 1, 22.697],
       [45, 1, 1, 0, 17.95

In [10]:
y #Viewing the dependent variable after encoding.

array([0, 3, 3, 4, 0, 4, 0, 3, 0, 0, 3, 0, 0, 0, 4, 0, 4, 1, 3, 0, 0, 0,
       0, 0, 0, 0, 0, 4, 0, 0, 4, 2, 4, 0, 4, 4, 1, 4, 4, 4, 0, 2, 0, 4,
       4, 4, 1, 3, 0, 0, 0, 4, 0, 0, 2, 3, 2, 0, 4, 0, 0, 1, 0, 4, 2, 0,
       1, 4, 0, 0, 2, 0, 4, 0, 0, 0, 1, 0, 1, 4, 2, 4, 3, 1, 3, 2, 4, 0,
       0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1, 1, 3, 4, 0, 4, 4, 0, 2, 0,
       1, 4, 4, 4, 4, 0, 4, 4, 1, 0, 0, 0, 0, 0, 2, 0, 0, 4, 0, 4, 0, 0,
       4, 0, 0, 4, 2, 1, 2, 4, 1, 0, 2, 0, 1, 4, 4, 1, 4, 3, 1, 2, 4, 4,
       0, 3, 1, 0, 3, 4, 4, 2, 4, 0, 0, 0, 0, 4, 0, 1, 4, 4, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 4, 4, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 3, 0, 3, 3, 4,
       4, 4])

# **Encoding categorical features**

In [11]:
import numpy as np #Importing numpy package as np
from sklearn.compose import ColumnTransformer #Importing columntransfer classs from scikit learn
from sklearn.preprocessing import OneHotEncoder #Importing onehotencoder class from scikit learn
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough') #Instantiating columntransfer class
X = np.array(ct.fit_transform(X)) #Transform the blood pressure level with the help of column transfer and transforming it into an numpy array
print(X)

[[1.0 0.0 0.0 ... 0 0 25.355]
 [0.0 1.0 0.0 ... 1 0 13.093]
 [0.0 1.0 0.0 ... 1 0 10.113999999999999]
 ...
 [0.0 0.0 1.0 ... 1 0 9.894]
 [0.0 0.0 1.0 ... 1 1 14.02]
 [0.0 1.0 0.0 ... 0 1 11.349]]


In [12]:
X=X[:,1:] #Removing one of the categorical values of blood pressure level inorder to avoid dummy variable trap.

In [13]:
X

array([[0.0, 0.0, 23, 0, 0, 25.355],
       [1.0, 0.0, 47, 1, 0, 13.093],
       [1.0, 0.0, 47, 1, 0, 10.113999999999999],
       ...,
       [0.0, 1.0, 52, 1, 0, 9.894],
       [0.0, 1.0, 23, 1, 1, 14.02],
       [1.0, 0.0, 40, 0, 1, 11.349]], dtype=object)

In [14]:
y

array([0, 3, 3, 4, 0, 4, 0, 3, 0, 0, 3, 0, 0, 0, 4, 0, 4, 1, 3, 0, 0, 0,
       0, 0, 0, 0, 0, 4, 0, 0, 4, 2, 4, 0, 4, 4, 1, 4, 4, 4, 0, 2, 0, 4,
       4, 4, 1, 3, 0, 0, 0, 4, 0, 0, 2, 3, 2, 0, 4, 0, 0, 1, 0, 4, 2, 0,
       1, 4, 0, 0, 2, 0, 4, 0, 0, 0, 1, 0, 1, 4, 2, 4, 3, 1, 3, 2, 4, 0,
       0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1, 1, 3, 4, 0, 4, 4, 0, 2, 0,
       1, 4, 4, 4, 4, 0, 4, 4, 1, 0, 0, 0, 0, 0, 2, 0, 0, 4, 0, 4, 0, 0,
       4, 0, 0, 4, 2, 1, 2, 4, 1, 0, 2, 0, 1, 4, 4, 1, 4, 3, 1, 2, 4, 4,
       0, 3, 1, 0, 3, 4, 4, 2, 4, 0, 0, 0, 0, 4, 0, 1, 4, 4, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 4, 4, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 3, 0, 3, 3, 4,
       4, 4])

In [15]:
from sklearn.model_selection import train_test_split #Importing train and test split from scikit learn library.
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0) #Allocating train and test variables with a test soze of 20%.

## **Feature Scaling**

In [16]:
from sklearn.preprocessing import StandardScaler #Importing standardscaler class from scikit learn library
sc=StandardScaler() #Creating an instance for StandardScaler class.
X_train=sc.fit_transform(X_train) #Performing feature scaling for the training set.
X_test=sc.transform(X_test) #Performing feature scaling for the test set.

# **Naive bayes classifier implementation**

In [17]:
from sklearn.naive_bayes import GaussianNB #Importing the gaussianNB class from scikit learn.
nb_classifier=GaussianNB() #Creating instance for naive bayes classifier.
nb_classifier.fit(X_train,y_train) #Training our model with the data.

GaussianNB(priors=None, var_smoothing=1e-09)

In [18]:
nb_classifier.score(X_test,y_test) #Evaluating our naive bayes classifier model performance

0.8

# **Implementation of K-fold Cross validation**

In [19]:
from sklearn.model_selection import cross_val_score #Importing cross validation class from scikit learn library.
acc=cross_val_score(estimator=nb_classifier,X=X_train,y=y_train,cv=10) #Evaluating the naive bayes classifier model with a cross validation split of 10.

In [20]:
acc.mean() #Obtaining the mean of 10 test fold accuracies.

0.8

In [21]:
acc.std() 

0.09185586535436918

In [22]:
#Blood pressure is the multicategorical variable in the training variable 
X[0]
#In the below statement the blood pressure is referred to as "High"

array([0.0, 0.0, 23, 0, 0, 25.355], dtype=object)

# **Sample prediction from user input**

In [23]:
age=int(input("Age of the patient : "))
gen=input("Gender of the patient : (M/F)")
bp=input("Enter the Blood pressure of the patient : (HIGH/LOW/NORMAL) :")
chol=input("Enter the Cholestrol level of the patient : (HIGH/NORMAL) :")
sodtopot=float(input("Enter the sodium to potassium ration in blood of the patient :"))
temp1=0
temp2=0
gen1=0
ch=0
if bp=="HIGH":
  temp1=0.0
  temp2=0.0
elif bp=="LOW":
  temp1=1.0
  temp2=0.0
elif bp=="NORMAL":
  temp1=0.0
  temp2=1.0
if gen=="M":
  gen1=1
elif gen=="F":
  gen1=0
if chol=="HIGH":
  ch=0
elif chol=="NORMAL":
  ch=1
result=int(nb_classifier.predict(sc.transform([[temp1,temp2,age,gen1,ch,sodtopot]])))
if result==0:
  print("DrugY")
elif result==1:
  print("drugA")
elif result==2:
  print("drugB")
elif result==3:
  print("drugC")
elif result==4:
  print("drugX")


Age of the patient : 24
Gender of the patient : (M/F)M
Enter the Blood pressure of the patient : (HIGH/LOW/NORMAL) :LOW
Enter the Cholestrol level of the patient : (HIGH/NORMAL) :HIGH
Enter the sodium to potassium ration in blood of the patient :23.4
drugC
